export const FETCH_WALLETS = 'FETCH_WALLETS';
export const FETCH_WALLETS_SUCCESS = 'FETCH_WALLETS_SUCCESS';
export const FETCH_WALLETS_FAILURE = 'FETCH_WALLETS_FAILURE';
export const RESET_WALLETS = 'RESET_WALLETS';
