export const FETCH_EXCHANGE_RATES = 'FETCH_EXCHANGE_RATES';
export const FETCH_EXCHANGE_RATES_SUCCESS = 'FETCH_EXCHANGE_RATES_SUCCESS';
export const FETCH_EXCHANGE_RATES_FAILURE = 'FETCH_EXCHANGE_RATES_FAILURE';
export const RESET_EXCHANGE_RATES = 'RESET_EXCHANGE_RATES';
export const CHANGE_EXCHANGE_FROM_AMOUNT = 'CHANGE_EXCHANGE_FROM_AMOUNT';
export const CHANGE_EXCHANGE_TO_AMOUNT = 'CHANGE_EXCHANGE_TO_AMOUNT';

export const APP_ID = '41f49319c571476684161aa566dd3dfa';
export const BASE_CURRENCY = 'usd';
