export const FETCH_EXCHANGE_RATES = 'FETCH_EXCHANGE_RATES';
export const FETCH_EXCHANGE_RATES_SUCCESS = 'FETCH_EXCHANGE_RATES_SUCCESS';
export const FETCH_EXCHANGE_RATES_FAILURE = 'FETCH_EXCHANGE_RATES_FAILURE';
export const RESET_EXCHANGE = 'RESET_EXCHANGE';
export const CHANGE_EXCHANGE_FROM = 'CHANGE_EXCHANGE_FROM';
export const CHANGE_EXCHANGE_FROM_SUCCESS = 'CHANGE_EXCHANGE_FROM_SUCCESS';
export const CHANGE_EXCHANGE_TO = 'CHANGE_EXCHANGE_TO';
export const CHANGE_EXCHANGE_TO_SUCCESS = 'CHANGE_EXCHANGE_TO_SUCCESS';
export const CHANGE_WALLET = 'CHANGE_WALLET';
export const CHANGE_WALLET_SUCCESS = 'CHANGE_WALLET_SUCCESS';

export const APP_ID = '41f49319c571476684161aa566dd3dfa';
export const BASE_CURRENCY = 'USD';
